import type { DrinkRecipe } from '../types/game';

export const DRINK_RECIPES: DrinkRecipe[] = [
  { id: 'cafe-coado', name: 'Cafe Coado', category: 'espresso', price: 5, profit: 3, prepTime: 5, unlockLevel: 1, icon: '☕', funFact: 'Metodo mais popular do Brasil, responsavel por 80% do consumo nacional.' },
  { id: 'espresso', name: 'Espresso', category: 'espresso', price: 7, profit: 4, prepTime: 8, unlockLevel: 1, icon: '☕', funFact: '30ml extraidos em 25-30 segundos, inventado na Italia em 1906.', requiredMachine: 'espresso-basica' },
  { id: 'espresso-duplo', name: 'Espresso Duplo', category: 'espresso', price: 9, profit: 5, prepTime: 10, unlockLevel: 2, icon: '☕', funFact: 'Tambem chamado de doppio, o dobro da dose.', requiredMachine: 'espresso-basica' },
  { id: 'americano', name: 'Americano', category: 'espresso', price: 8, profit: 5, prepTime: 7, unlockLevel: 2, icon: '☕', funFact: 'Nasceu na Segunda Guerra Mundial quando soldados diluiam espresso.', requiredMachine: 'espresso-basica' },
  { id: 'ristretto', name: 'Ristretto', category: 'espresso', price: 8, profit: 5, prepTime: 8, unlockLevel: 3, icon: '☕', funFact: 'Apenas 15-20ml, mais concentrado que o espresso.', requiredMachine: 'espresso-basica' },
  { id: 'lungo', name: 'Lungo', category: 'espresso', price: 8, profit: 4, prepTime: 8, unlockLevel: 3, icon: '☕', funFact: 'Extracao mais longa, sabor mais suave que o espresso.', requiredMachine: 'espresso-basica' },
  { id: 'cafe-turco', name: 'Cafe Turco', category: 'espresso', price: 10, profit: 6, prepTime: 12, unlockLevel: 4, icon: '☕', funFact: 'Preparado em cezve desde o seculo XVI, Patrimonio da UNESCO.', requiredMachine: 'chaleira-eletrica' },
  { id: 'red-eye', name: 'Red Eye', category: 'espresso', price: 11, profit: 7, prepTime: 10, unlockLevel: 4, icon: '☕', funFact: 'Coado + shot de espresso para uma dose extra de cafeina.', requiredMachine: 'espresso-basica' },
  { id: 'cafe-pingado', name: 'Cafe Pingado', category: 'espresso', price: 6, profit: 3, prepTime: 5, unlockLevel: 5, icon: '☕', funFact: 'Classico brasileiro com gota de leite — simples e perfeito.' },
  { id: 'macchiato', name: 'Macchiato', category: 'espresso', price: 9, profit: 5, prepTime: 8, unlockLevel: 5, icon: '☕', funFact: 'Espresso manchado com espuma — "macchiato" e italiano para "manchado".', requiredMachine: 'espresso-basica' },

  { id: 'cappuccino', name: 'Cappuccino', category: 'leite', price: 12, profit: 7, prepTime: 12, unlockLevel: 6, icon: '🥛', funFact: '1/3 espresso, 1/3 leite, 1/3 espuma — nome dos monges Capuchinhos.', requiredMachine: 'vaporizador' },
  { id: 'latte', name: 'Latte', category: 'leite', price: 14, profit: 8, prepTime: 15, unlockLevel: 6, icon: '🥛', funFact: 'Leite vaporizado com shot de espresso, arte em cada xicara.', requiredMachine: 'vaporizador' },
  { id: 'flat-white', name: 'Flat White', category: 'leite', price: 15, profit: 9, prepTime: 12, unlockLevel: 7, icon: '🥛', funFact: 'Originario da Australia/Nova Zelandia, microespuma sedosa.', requiredMachine: 'vaporizador' },
  { id: 'mocha', name: 'Mocha', category: 'leite', price: 16, profit: 9, prepTime: 18, unlockLevel: 8, icon: '🍫', funFact: 'Latte + chocolate, indulgencia pura. Nome vem de Mocha no Yemen.', requiredMachine: 'vaporizador' },
  { id: 'chai-latte', name: 'Chai Latte', category: 'leite', price: 14, profit: 8, prepTime: 14, unlockLevel: 8, icon: '🫖', funFact: 'Cha masala indiano com leite — especiarias que aquecem a alma.', requiredMachine: 'vaporizador' },
  { id: 'cafe-com-leite', name: 'Cafe com Leite', category: 'leite', price: 8, profit: 5, prepTime: 6, unlockLevel: 9, icon: '🥛', funFact: 'O classico do Brasil, presente em todo cafe da manha.' },
  { id: 'cortado', name: 'Cortado', category: 'leite', price: 11, profit: 7, prepTime: 8, unlockLevel: 9, icon: '🥛', funFact: 'Espresso cortado com leite morno — equilibrio perfeito.', requiredMachine: 'vaporizador' },
  { id: 'breve', name: 'Breve', category: 'leite', price: 15, profit: 9, prepTime: 14, unlockLevel: 10, icon: '🥛', funFact: 'Espresso com half-and-half cremoso, textura aveludada.', requiredMachine: 'vaporizador' },
  { id: 'bombon', name: 'Bombon', category: 'leite', price: 13, profit: 8, prepTime: 10, unlockLevel: 11, icon: '🍯', funFact: 'Espresso com leite condensado — doce e forte.', requiredMachine: 'espresso-basica' },
  { id: 'vienna-coffee', name: 'Vienna Coffee', category: 'leite', price: 14, profit: 8, prepTime: 12, unlockLevel: 12, icon: '🍨', funFact: 'Espresso coberto com chantilly — elegancia vienense.', requiredMachine: 'vaporizador' },

  { id: 'cold-brew', name: 'Cold Brew', category: 'gelados', price: 16, profit: 10, prepTime: 20, unlockLevel: 13, icon: '🧊', funFact: '12-24h de infusao a frio, 67% menos acidez.', requiredMachine: 'cold-brew-tower' },
  { id: 'iced-latte', name: 'Iced Latte', category: 'gelados', price: 15, profit: 9, prepTime: 15, unlockLevel: 13, icon: '🧊', funFact: 'Espresso + leite sobre gelo, o mais vendido no verao.', requiredMachine: 'cold-brew-tower' },
  { id: 'frappe', name: 'Frappe', category: 'gelados', price: 17, profit: 10, prepTime: 18, unlockLevel: 14, icon: '🧊', funFact: 'Cafe batido com gelo, inventado acidentalmente na Grecia em 1957.', requiredMachine: 'cold-brew-tower' },
  { id: 'nitro-coffee', name: 'Nitro Coffee', category: 'gelados', price: 22, profit: 14, prepTime: 25, unlockLevel: 15, icon: '🍺', funFact: 'Cold brew infusado com nitrogenio, textura cremosa sem leite.', requiredMachine: 'nitro-tap' },
  { id: 'affogato', name: 'Affogato', category: 'gelados', price: 18, profit: 11, prepTime: 12, unlockLevel: 16, icon: '🍨', funFact: 'Sorvete de baunilha afogado em espresso — sobremesa + cafe.', requiredMachine: 'cold-brew-tower' },
  { id: 'iced-mocha', name: 'Iced Mocha', category: 'gelados', price: 18, profit: 11, prepTime: 18, unlockLevel: 16, icon: '🧊', funFact: 'Mocha gelado, perfeito pro verao brasileiro.', requiredMachine: 'cold-brew-tower' },
  { id: 'cafe-gelado-br', name: 'Cafe Gelado Brasileiro', category: 'gelados', price: 12, profit: 7, prepTime: 10, unlockLevel: 17, icon: '🧊', funFact: 'Cafe coado gelado com acucar — refrescante e simples.' },
  { id: 'mazagran', name: 'Mazagran', category: 'gelados', price: 14, profit: 8, prepTime: 14, unlockLevel: 18, icon: '🍋', funFact: 'O primeiro cafe gelado da historia, com limao.', requiredMachine: 'cold-brew-tower' },
  { id: 'japanese-iced', name: 'Japanese Iced Coffee', category: 'gelados', price: 16, profit: 10, prepTime: 16, unlockLevel: 19, icon: '🧊', funFact: 'Coado direto sobre gelo para flash-chilling perfeito.', requiredMachine: 'v60-station' },
  { id: 'espresso-tonic', name: 'Tonica com Espresso', category: 'gelados', price: 19, profit: 12, prepTime: 14, unlockLevel: 20, icon: '🍹', funFact: 'Espresso + agua tonica + gelo — sofisticado e refrescante.', requiredMachine: 'cold-brew-tower' },

  { id: 'v60', name: 'V60 Single Origin', category: 'specialty', price: 25, profit: 16, prepTime: 30, unlockLevel: 21, icon: '⭐', funFact: 'Filtro conico japones da Hario, extracao precisa desde 2005.', requiredMachine: 'v60-station' },
  { id: 'chemex', name: 'Chemex', category: 'specialty', price: 28, profit: 18, prepTime: 35, unlockLevel: 22, icon: '⭐', funFact: 'Design iconico no MoMA desde 1943, sabor limpo e brilhante.', requiredMachine: 'v60-station' },
  { id: 'aeropress', name: 'AeroPress', category: 'specialty', price: 22, profit: 14, prepTime: 20, unlockLevel: 23, icon: '⭐', funFact: 'Inventado em 2005 por Alan Adler, criador do frisbee Aerobie.', requiredMachine: 'v60-station' },
  { id: 'siphon', name: 'Siphon', category: 'specialty', price: 35, profit: 22, prepTime: 40, unlockLevel: 24, icon: '⭐', funFact: 'Teatro visual com pressao de vapor, sabor limpo e delicado.', requiredMachine: 'siphon-bar' },
  { id: 'moka', name: 'Moka', category: 'specialty', price: 20, profit: 13, prepTime: 18, unlockLevel: 25, icon: '⭐', funFact: 'A cafeteira italiana Bialetti classica desde 1933.', requiredMachine: 'espresso-basica' },
  { id: 'french-press', name: 'French Press', category: 'specialty', price: 18, profit: 11, prepTime: 22, unlockLevel: 25, icon: '⭐', funFact: 'Imersao total, corpo encorpado — o metodo mais democratico.' },
  { id: 'turkish-sand', name: 'Turkish Sand Coffee', category: 'specialty', price: 30, profit: 19, prepTime: 35, unlockLevel: 26, icon: '⭐', funFact: 'Preparado em areia quente, tradicao milenar turca.', requiredMachine: 'siphon-bar' },
  { id: 'espresso-tonic-rosemary', name: 'Espresso Tonic Alecrim', category: 'specialty', price: 28, profit: 18, prepTime: 16, unlockLevel: 27, icon: '🌿', funFact: 'Tonica + alecrim fresco — artesanal e botanico.', requiredMachine: 'cold-brew-tower' },
  { id: 'drip-specialty', name: 'Drip Specialty', category: 'specialty', price: 32, profit: 20, prepTime: 30, unlockLevel: 28, icon: '⭐', funFact: 'Microlote single origin, coado com precisao artesanal.', requiredMachine: 'v60-station' },
  { id: 'cafe-jacu', name: 'Cafe de Jacu', category: 'specialty', price: 45, profit: 30, prepTime: 45, unlockLevel: 30, icon: '👑', funFact: 'O cafe mais exclusivo do Brasil, processado pelo passaro Jacu.', requiredMachine: 'siphon-bar' },
];
