import type { DrinkRecipe } from '../types/game';

export const DRINK_RECIPES: DrinkRecipe[] = [
  {
    id: 'cafe-coado',
    name: 'Cafe Coado',
    category: 'espresso',
    price: 5,
    profit: 3,
    prepTime: 5,
    unlockLevel: 1,
    icon: '☕',
    funFact: 'O coado e o metodo mais popular no Brasil, responsavel por 80% do consumo nacional.',
  },
  {
    id: 'espresso',
    name: 'Espresso',
    category: 'espresso',
    price: 7,
    profit: 4,
    prepTime: 8,
    unlockLevel: 2,
    icon: '☕',
    funFact: 'O espresso foi inventado na Italia em 1906 e deve ser extraido em 25-30 segundos.',
    requiredMachine: 'espresso-basica',
  },
  {
    id: 'americano',
    name: 'Americano',
    category: 'espresso',
    price: 8,
    profit: 5,
    prepTime: 7,
    unlockLevel: 3,
    icon: '☕',
    funFact: 'O Americano surgiu na 2a Guerra, quando soldados americanos diluiam espresso italiano.',
    requiredMachine: 'espresso-basica',
  },
  {
    id: 'ristretto',
    name: 'Ristretto',
    category: 'espresso',
    price: 9,
    profit: 6,
    prepTime: 10,
    unlockLevel: 4,
    icon: '☕',
    funFact: 'O Ristretto usa metade da agua do espresso, resultando num sabor mais concentrado.',
    requiredMachine: 'espresso-basica',
  },
  {
    id: 'lungo',
    name: 'Lungo',
    category: 'espresso',
    price: 8,
    profit: 5,
    prepTime: 8,
    unlockLevel: 5,
    icon: '☕',
    funFact: 'Lungo significa "longo" em italiano — usa o dobro de agua do espresso.',
    requiredMachine: 'espresso-basica',
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    category: 'leite',
    price: 12,
    profit: 7,
    prepTime: 12,
    unlockLevel: 6,
    icon: '🥛',
    funFact: 'O Cappuccino leva o nome dos monges Capuchinhos, pela cor de seus habitos.',
    requiredMachine: 'vaporizador',
  },
  {
    id: 'latte',
    name: 'Latte',
    category: 'leite',
    price: 14,
    profit: 8,
    prepTime: 15,
    unlockLevel: 7,
    icon: '🥛',
    funFact: 'Latte Art surgiu nos anos 80 em Seattle e virou forma de expressao artistica.',
    requiredMachine: 'vaporizador',
  },
  {
    id: 'flat-white',
    name: 'Flat White',
    category: 'leite',
    price: 15,
    profit: 9,
    prepTime: 12,
    unlockLevel: 8,
    icon: '🥛',
    funFact: 'Australia e Nova Zelandia disputam quem inventou o Flat White nos anos 80.',
    requiredMachine: 'vaporizador',
  },
  {
    id: 'macchiato',
    name: 'Macchiato',
    category: 'leite',
    price: 10,
    profit: 6,
    prepTime: 10,
    unlockLevel: 9,
    icon: '🥛',
    funFact: 'Macchiato significa "manchado" — e um espresso com apenas uma gota de leite.',
    requiredMachine: 'vaporizador',
  },
  {
    id: 'mocha',
    name: 'Mocha',
    category: 'leite',
    price: 16,
    profit: 9,
    prepTime: 18,
    unlockLevel: 10,
    icon: '🍫',
    funFact: 'O Mocha vem da cidade de Mocha no Yemen, um dos primeiros portos de cafe do mundo.',
    requiredMachine: 'vaporizador',
  },
  {
    id: 'cortado',
    name: 'Cortado',
    category: 'leite',
    price: 11,
    profit: 7,
    prepTime: 8,
    unlockLevel: 11,
    icon: '🥛',
    funFact: 'Cortado e espanhol e significa "cortado" — o leite corta a acidez do cafe.',
    requiredMachine: 'vaporizador',
  },
  {
    id: 'affogato',
    name: 'Affogato',
    category: 'leite',
    price: 18,
    profit: 11,
    prepTime: 15,
    unlockLevel: 12,
    icon: '🍨',
    funFact: 'Affogato e italiano para "afogado" — sorvete afogado em espresso quente.',
    requiredMachine: 'vaporizador',
  },
  {
    id: 'cold-brew',
    name: 'Cold Brew',
    category: 'gelados',
    price: 16,
    profit: 10,
    prepTime: 20,
    unlockLevel: 13,
    icon: '🧊',
    funFact: 'Cold Brew e preparado com agua fria por 12-24 horas, resultando em 67% menos acidez.',
    requiredMachine: 'cold-brew-tower',
  },
  {
    id: 'iced-latte',
    name: 'Iced Latte',
    category: 'gelados',
    price: 15,
    profit: 9,
    prepTime: 15,
    unlockLevel: 14,
    icon: '🧊',
    funFact: 'O Iced Latte e o drink mais vendido no verao em cafeterias ao redor do mundo.',
    requiredMachine: 'cold-brew-tower',
  },
  {
    id: 'frappe',
    name: 'Frappe',
    category: 'gelados',
    price: 18,
    profit: 10,
    prepTime: 20,
    unlockLevel: 15,
    icon: '🧊',
    funFact: 'O Frappe foi inventado acidentalmente em 1957 na Grecia durante uma feira comercial.',
    requiredMachine: 'cold-brew-tower',
  },
  {
    id: 'espresso-tonic',
    name: 'Espresso Tonic',
    category: 'gelados',
    price: 20,
    profit: 12,
    prepTime: 15,
    unlockLevel: 17,
    icon: '🍹',
    funFact: 'Espresso Tonic surgiu na Escandinavia e conquistou o mundo specialty em 2015.',
    requiredMachine: 'cold-brew-tower',
  },
  {
    id: 'nitro-coffee',
    name: 'Nitro Coffee',
    category: 'gelados',
    price: 22,
    profit: 14,
    prepTime: 25,
    unlockLevel: 19,
    icon: '🍺',
    funFact: 'Nitro Coffee usa nitrogenio para criar uma textura cremosa sem adicionar leite.',
    requiredMachine: 'nitro-tap',
  },
  {
    id: 'v60',
    name: 'V60 Single Origin',
    category: 'specialty',
    price: 25,
    profit: 16,
    prepTime: 30,
    unlockLevel: 21,
    icon: '⭐',
    funFact: 'A V60 da Hario foi criada em 2005 no Japao e revolucionou o cafe filtrado.',
    requiredMachine: 'v60-station',
  },
  {
    id: 'chemex',
    name: 'Chemex',
    category: 'specialty',
    price: 28,
    profit: 18,
    prepTime: 35,
    unlockLevel: 23,
    icon: '⭐',
    funFact: 'A Chemex de 1941 esta no acervo do MoMA como um dos melhores designs do seculo.',
    requiredMachine: 'v60-station',
  },
  {
    id: 'aeropress',
    name: 'AeroPress',
    category: 'specialty',
    price: 22,
    profit: 14,
    prepTime: 20,
    unlockLevel: 25,
    icon: '⭐',
    funFact: 'O AeroPress foi inventado pelo mesmo criador do frisbee Aerobie em 2005.',
    requiredMachine: 'v60-station',
  },
  {
    id: 'siphon',
    name: 'Siphon',
    category: 'specialty',
    price: 35,
    profit: 22,
    prepTime: 40,
    unlockLevel: 27,
    icon: '⭐',
    funFact: 'O Siphon usa pressao de vapor e parece um experimento de quimica — e puro teatro!',
    requiredMachine: 'siphon-bar',
  },
  {
    id: 'turkish',
    name: 'Cafe Turco',
    category: 'specialty',
    price: 20,
    profit: 13,
    prepTime: 25,
    unlockLevel: 29,
    icon: '⭐',
    funFact: 'O Cafe Turco e Patrimonio Cultural Imaterial da UNESCO desde 2013.',
    requiredMachine: 'siphon-bar',
  },
];
