import type { Machine } from '../types/game';

export const MACHINES: Machine[] = [
  {
    id: 'cafeteira-simples',
    name: 'Cafeteira Simples',
    cost: 0,
    unlockLevel: 1,
    icon: '☕',
    speedBonus: 0,
    qualityBonus: 0,
    capacity: 1,
    maxLevel: 5,
    description: 'Coador de pano tradicional para comecar. Faz cafe coado.',
  },
  {
    id: 'chaleira-eletrica',
    name: 'Chaleira Eletrica',
    cost: 500,
    unlockLevel: 4,
    icon: '🫖',
    speedBonus: 0.05,
    qualityBonus: 0.05,
    capacity: 1,
    maxLevel: 5,
    description: 'Chaleira com controle de temperatura. Habilita Cafe Turco.',
  },
  {
    id: 'espresso-basica',
    name: 'Maquina Espresso',
    cost: 2000,
    unlockLevel: 2,
    icon: '☕',
    speedBonus: 0.1,
    qualityBonus: 0.05,
    capacity: 2,
    maxLevel: 5,
    description: 'Maquina de espresso basica. Habilita drinks a base de espresso.',
  },
  {
    id: 'vaporizador',
    name: 'Vaporizador de Leite',
    cost: 3000,
    unlockLevel: 6,
    icon: '🥛',
    speedBonus: 0.05,
    qualityBonus: 0.1,
    capacity: 2,
    maxLevel: 5,
    description: 'Vaporiza leite para cappuccinos, lattes e mais.',
  },
  {
    id: 'cold-brew-tower',
    name: 'Refrigerador',
    cost: 5000,
    unlockLevel: 13,
    icon: '🧊',
    speedBonus: 0.15,
    qualityBonus: 0.1,
    capacity: 3,
    maxLevel: 5,
    description: 'Refrigerador completo. Habilita drinks gelados.',
  },
  {
    id: 'espresso-dupla',
    name: 'Espresso Dupla Boca',
    cost: 8000,
    unlockLevel: 10,
    icon: '☕',
    speedBonus: 0.2,
    qualityBonus: 0.15,
    capacity: 3,
    maxLevel: 5,
    description: 'Maquina de espresso com duas bocas. Muito mais rapida.',
  },
  {
    id: 'v60-station',
    name: 'V60 Station',
    cost: 8000,
    unlockLevel: 19,
    icon: '⭐',
    speedBonus: 0.1,
    qualityBonus: 0.2,
    capacity: 2,
    maxLevel: 5,
    description: 'Estacao para metodos filtrados: V60, Chemex, AeroPress.',
  },
  {
    id: 'nitro-tap',
    name: 'Cold Brew Tower',
    cost: 15000,
    unlockLevel: 15,
    icon: '🍺',
    speedBonus: 0.2,
    qualityBonus: 0.15,
    capacity: 4,
    maxLevel: 5,
    description: 'Torre Kyoto de cold drip com sistema de nitrogenio.',
  },
  {
    id: 'la-marzocca',
    name: 'La Marzocca GB5',
    cost: 25000,
    unlockLevel: 20,
    icon: '👑',
    speedBonus: 0.3,
    qualityBonus: 0.25,
    capacity: 4,
    maxLevel: 5,
    description: 'A maquina dos sonhos. 4 drinks simultaneos, -30% tempo.',
  },
  {
    id: 'siphon-bar',
    name: 'Siphon Setup',
    cost: 50000,
    unlockLevel: 24,
    icon: '🔬',
    speedBonus: 0.1,
    qualityBonus: 0.25,
    capacity: 2,
    maxLevel: 5,
    description: 'Bar de siphon para drinks teatrais e premium.',
  },
  {
    id: 'slayer-espresso',
    name: 'Slayer Espresso',
    cost: 100000,
    unlockLevel: 28,
    icon: '🏆',
    speedBonus: 0.5,
    qualityBonus: 0.3,
    capacity: 5,
    maxLevel: 5,
    description: 'A ultimate machine. 5 drinks simultaneos, -50% tempo.',
  },
];

export function getMachineCost(baseCost: number, level: number): number {
  return Math.floor(baseCost * Math.pow(2.5, level));
}
