import type { MiniEvent } from '../types/game';

export const MINI_EVENTS: MiniEvent[] = [
  {
    id: 'tourist-group',
    title: 'Grupo de Turistas!',
    description: 'Um grupo de turistas entrou na sua cafeteria. Clientes pagam 2x por 2 minutos!',
    icon: '🌍',
    effect: { type: 'moneyBoost', multiplier: 2 },
    duration: 120000,
  },
  {
    id: 'rain',
    title: 'Dia de Chuva!',
    description: 'Esta chovendo la fora. Mais clientes querem um cafe quente! +100% clientes por 2min.',
    icon: '🌧️',
    effect: { type: 'customerBoost', multiplier: 2 },
    duration: 120000,
  },
  {
    id: 'influencer-visit',
    title: 'Influencer na Area!',
    description: 'Um influencer famoso quer tirar foto na sua cafeteria. +50% reputacao por 3min!',
    icon: '📸',
    effect: { type: 'reputationBoost', multiplier: 1.5 },
    duration: 180000,
  },
  {
    id: 'happy-hour',
    title: 'Happy Hour!',
    description: 'E hora do happy hour! Todos os drinks rendem 50% mais lucro por 2min.',
    icon: '🎉',
    effect: { type: 'moneyBoost', multiplier: 1.5 },
    duration: 120000,
  },
  {
    id: 'coffee-festival',
    title: 'Festival do Cafe!',
    description: 'Tem um festival de cafe na cidade. Triplo de clientes por 2 minutos!',
    icon: '☕',
    effect: { type: 'customerBoost', multiplier: 3 },
    duration: 120000,
  },
  {
    id: 'review-bomb',
    title: 'Onda de Reviews!',
    description: 'Seu cafe foi mencionado num blog. Reputacao sobe mais rapido por 3min!',
    icon: '⭐',
    effect: { type: 'reputationBoost', multiplier: 2 },
    duration: 180000,
  },
  {
    id: 'rush-hour',
    title: 'Hora do Rush!',
    description: 'O escritorio ao lado saiu pro cafe. Dobro de clientes por 2min!',
    icon: '🏃',
    effect: { type: 'customerBoost', multiplier: 2 },
    duration: 120000,
  },
  {
    id: 'celebrity-sighting',
    title: 'Celebridade Avistada!',
    description: 'Uma celebridade foi vista na sua cafeteria! Todos querem vir. +150% clientes!',
    icon: '🌟',
    effect: { type: 'customerBoost', multiplier: 2.5 },
    duration: 120000,
  },
  {
    id: 'barista-day',
    title: 'Dia do Barista!',
    description: 'E o dia internacional do barista. Drinks com +100% qualidade por 3min!',
    icon: '👨‍🍳',
    effect: { type: 'moneyBoost', multiplier: 2 },
    duration: 180000,
  },
  {
    id: 'special-bean',
    title: 'Grao Especial!',
    description: 'Voce recebeu um lote de graos raros. Todos os drinks rendem 3x por 1min!',
    icon: '💎',
    effect: { type: 'moneyBoost', multiplier: 3 },
    duration: 60000,
  },
];
